language: android
jdk: oraclejdk8
sudo: false
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-28

    # The SDK version used to compile your project
    - android-28

    # Additional components
    #- extra-google-google_play_services
    #- extra-google-m2repository
    #- extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-x86-android-28
    - sys-img-armeabi-v7a-android-28
    
before_install:
#  - yes | sdkmanager "platforms;android-28"
  - chmod +x gradlew
  - mkdir -p "$ANDROID_HOME/licenses"
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - yes | sdkmanager --update
  - yes | sdkmanager --licenses
  # Setup emulator
  #- echo "no" | avdmanager create avd -n test -k "system-images;android-28;default;armeabi-v7a" -c 200M -f & # &>/dev/null
  #- $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window & # &>/dev/null


#before_cache:
#  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
#  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
#cache:
#  directories:
#    - $HOME/.gradle/caches/
#    - $HOME/.gradle/wrapper/
#    - $HOME/.android/build-cache

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - echo no | android create avd --force -n test -t android-28 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0.0
  - adb shell settings put global transition_animation_scale 0.0
  - adb shell settings put global animator_duration_scale 0.0

script: echo yes | ./gradlew build connectedCheck connectedAndroidTest --scan
